apiVersion: agentprovider/v1
kind: Resource
type: awx_job

connection:
    base_url: ${env.AWX}
    allow_insecure: true
    allow_private_host: true
    headers:
        Content-Type: application/json
    auth:
        type: basic
        username: ${env.AWX_USERNAME}
        password: ${env.AWX_PASSWORD}

schema:
    attributes:
        template_id:
            type: number
            required: true
        id:
            type: number
            computed: true
        job:
            type: number
            computed: true
            field: job
        status:
            type: string
            computed: true
        name:
            type: string
            computed: true
        job_type:
            type: string
            computed: true

ignore_server_fields:
    - related
    - summary_fields
    - url
    - type
    - created
    - modified
    - unified_job_template
    - launch_type
    - started
    - finished
    - canceled_on
    - elapsed
    - execution_node
    - controller_node
    - execution_environment
    - job_args
    - job_cwd
    - job_env
    - result_traceback
    - event_processing_finished
    - job_explanation
    - scm_branch
    - scm_revision
    - extra_vars
    - limit
    - diff_mode
    - timeout
    - forks
    - verbosity
    - job_slice_count
    - job_slice_number
    - job_tags
    - skip_tags
    - start_at_task
    - force_handlers
    - allow_simultaneous
    - use_fact_cache
    - playbook
    - project
    - organization
    - inventory
    - job_template
    - artifacts
    - instance_group
    - failed
    - passwords_needed_to_start
    - webhook_service
    - webhook_credential
    - webhook_guid
    - description
    - ignored_fields
    - work_unit_id
    - launched_by

actions:
    launch:
        method: POST
        path: /api/v2/job_templates/${template_id}/launch/
        expect_status:
            - 201

conformance:
    action: launch
    example:
        template_id: 70
        status: pending
        name: ap-demo-jt-05290835
        job_type: run
    expect:
        id:
            not_null: true
        job:
            not_null: true
    invariants:
        - action_returns_expected
        - state_matches_expect
