apiVersion: agentprovider/v1
type: awx_job_template_ds
kind: DataSource

connection:
  base_url: ${env.AWX}
  allow_insecure: true
  allow_private_host: true
  headers:
    Content-Type: application/json
  auth:
    type: basic
    username: ${env.AWX_USERNAME}
    password: ${env.AWX_PASSWORD}

identity:
  attribute: id
  known_after: read
  response_field: id

schema:
  attributes:
    id:
      required: true
      type: string
    name:
      computed: true
      type: string
    description:
      computed: true
      type: string
    job_type:
      computed: true
      type: string
    inventory:
      computed: true
      type: number
    project:
      computed: true
      type: number
    playbook:
      computed: true
      type: string
    scm_branch:
      computed: true
      type: string
    forks:
      computed: true
      type: number
    limit:
      computed: true
      type: string
    verbosity:
      computed: true
      type: number
    extra_vars:
      computed: true
      type: string
    job_tags:
      computed: true
      type: string
    skip_tags:
      computed: true
      type: string
    timeout:
      computed: true
      type: number
    organization:
      computed: true
      type: number
    status:
      computed: true
      type: string
    survey_enabled:
      computed: true
      type: string
    become_enabled:
      computed: true
      type: string
    diff_mode:
      computed: true
      type: string
    allow_simultaneous:
      computed: true
      type: string
    job_slice_count:
      computed: true
      type: number

ignore_server_fields:
  - related
  - summary_fields
  - type
  - url
  - created
  - modified
  - last_job_run
  - last_job_failed
  - next_job_run
  - execution_environment
  - host_config_key
  - ask_scm_branch_on_launch
  - ask_diff_mode_on_launch
  - ask_variables_on_launch
  - ask_limit_on_launch
  - ask_tags_on_launch
  - ask_skip_tags_on_launch
  - ask_job_type_on_launch
  - ask_verbosity_on_launch
  - ask_inventory_on_launch
  - ask_credential_on_launch
  - ask_execution_environment_on_launch
  - ask_labels_on_launch
  - ask_forks_on_launch
  - ask_job_slice_count_on_launch
  - ask_timeout_on_launch
  - ask_instance_groups_on_launch
  - force_handlers
  - start_at_task
  - use_fact_cache
  - webhook_service
  - webhook_credential
  - prevent_instance_group_fallback
  - custom_virtualenv

lifecycle:
  read:
    method: GET
    path: "/api/v2/job_templates/${id}/"
    expect_status:
      - 200

conformance:
  example:
    id: "70"
    name: "ap-demo-jt-05290835"
    status: "successful"
  invariants:
    - read_returns_expected
    - state_matches_expect
  expect:
    name: "ap-demo-jt-05290835"
    status: "successful"
    id:
      not_null: true
