apiVersion: agentprovider/v1
kind: Resource
type: workflow_job
connection:
  base_url: ${env.AWX}
  allow_insecure: true
  allow_private_host: true
  auth:
    type: basic
    username: ${env.AWX_USERNAME}
    password: ${env.AWX_PASSWORD}
schema:
  attributes:
    workflow_job_template_id:
      type: number
      required: true
    id:
      type: number
      computed: true
    name:
      type: string
      computed: true
    status:
      type: string
      computed: true
    type:
      type: string
      computed: true
    launch_type:
      type: string
      computed: true
    workflow_job_template:
      type: number
      computed: true
actions:
  launch:
    method: POST
    path: "/api/v2/workflow_job_templates/${workflow_job_template_id}/launch/"
    expect_status:
      - 201
conformance:
  action: launch
  example:
    workflow_job_template_id: 173
    status: pending
    type: workflow_job
  expect:
    id:
      not_null: true
    name:
      not_null: true
  invariants:
    - action_returns_expected
    - state_matches_expect
